In [1]:
from sage.crypto.util import ascii_to_bin
from sage.crypto.util import bin_to_ascii
from sage.crypto.util import ascii_integer

In [2]:
bin = BinaryStrings()
B = bin.encoding("files");
list(B)

[0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1]

In [3]:
list1=list(B)

In [4]:
C = codes.BCHCode(GF(2), 15, 7, offset=1)
C

/opt/sagemath-9.3/local/lib/python3.7/site-packages/sage/coding/cyclic_code.py:452: FutureWarning: This class/method/function is marked as experimental. It, its functionality or its interface might change without a formal deprecation.
See http://trac.sagemath.org/20284 for details.
  embedding=F_to_Fsplit)


[15, 5] BCH Code over GF(2) with designed distance 7

In [5]:
G=C.generator_matrix()
G

[1 1 1 0 1 1 0 0 1 0 1 0 0 0 0]
[0 1 1 1 0 1 1 0 0 1 0 1 0 0 0]
[0 0 1 1 1 0 1 1 0 0 1 0 1 0 0]
[0 0 0 1 1 1 0 1 1 0 0 1 0 1 0]
[0 0 0 0 1 1 1 0 1 1 0 0 1 0 1]

In [6]:
print("length : ",len(list1))
len=len(list1)

length :  40


In [8]:
import numpy as np;
n=len//5
n
list1
 
splits = np.array_split(list1,n)
for array in splits:
    print(list(array))

[0, 1, 1, 0, 0]
[1, 1, 0, 0, 1]
[1, 0, 1, 0, 0]
[1, 0, 1, 1, 0]
[1, 1, 0, 0, 0]
[1, 1, 0, 0, 1]
[0, 1, 0, 1, 1]
[1, 0, 0, 1, 1]


In [9]:
#encoding
list2=[]
for array in splits:
    word = vector(GF(2),(array))
    E = codes.encoders.LinearCodeGeneratorMatrixEncoder(C)
    A=E.encode(word)
    list2.append(A)

list2
    
    

[(0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0),
 (1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1),
 (1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0),
 (1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0),
 (1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0),
 (1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1),
 (0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1),
 (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)]

In [10]:
#decoding
list3=[]
for x in list2:
    word = vector(GF(2), ((x)))
    w_err = word + vector(GF(2), ((1,0,0,0,0,0,0,0,0,0,0,0,0,0,0)))
    D = C.decoder()
    G=D.decode_to_message(w_err)
    list3.append(G)
list3

[(0, 1, 1, 0, 0),
 (1, 1, 0, 0, 1),
 (1, 0, 1, 0, 0),
 (1, 0, 1, 1, 0),
 (1, 1, 0, 0, 0),
 (1, 1, 0, 0, 1),
 (0, 1, 0, 1, 1),
 (1, 0, 0, 1, 1)]

In [11]:
for x in list3:
    print(x)

(0, 1, 1, 0, 0)
(1, 1, 0, 0, 1)
(1, 0, 1, 0, 0)
(1, 0, 1, 1, 0)
(1, 1, 0, 0, 0)
(1, 1, 0, 0, 1)
(0, 1, 0, 1, 1)
(1, 0, 0, 1, 1)


In [12]:
strg=[]
for x in list3:
    
    for y in x:
        strg.append(y)
        print(y)

0
1
1
0
0
1
1
0
0
1
1
0
1
0
0
1
0
1
1
0
1
1
0
0
0
1
1
0
0
1
0
1
0
1
1
1
0
0
1
1


In [13]:
binr = ''.join(str(e) for e in strg)
print(binr)

0110011001101001011011000110010101110011


In [14]:
binr

'0110011001101001011011000110010101110011'

In [15]:
word=bin_to_ascii(binr)
word

'files'