In [1]:
import numpy as np
from sage.crypto.util import ascii_to_bin
from sage.crypto.util import bin_to_ascii
from sage.crypto.util import ascii_integer

In [2]:
C = codes.BCHCode(GF(2), 15, 7, offset=1)
C

/opt/sagemath-9.3/local/lib/python3.7/site-packages/sage/coding/cyclic_code.py:452: FutureWarning: This class/method/function is marked as experimental. It, its functionality or its interface might change without a formal deprecation.
See http://trac.sagemath.org/20284 for details.
  embedding=F_to_Fsplit)


[15, 5] BCH Code over GF(2) with designed distance 7

In [3]:
G=C.generator_matrix()
G

[1 1 1 0 1 1 0 0 1 0 1 0 0 0 0]
[0 1 1 1 0 1 1 0 0 1 0 1 0 0 0]
[0 0 1 1 1 0 1 1 0 0 1 0 1 0 0]
[0 0 0 1 1 1 0 1 1 0 0 1 0 1 0]
[0 0 0 0 1 1 1 0 1 1 0 0 1 0 1]

In [4]:
inp = input("Enter any string : ")
print(inp)

Enter any string : Sagemath
Sagemath


In [5]:
bin = BinaryStrings()
B = ascii_to_bin(inp);
print("Converted to Binary",B)
list1=[int(i) for i in str(B)]


Converted to Binary 0101001101100001011001110110010101101101011000010111010001101000


In [6]:
print(list1)

[0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0]


In [7]:
len=len(list1)
len

64

In [8]:
pad = '0'
if len % 5 ==1:
    l=len+4
    x = str(B).ljust(l, pad)
    print(x)
elif len % 5 ==2:
    l=len+3
    x = str(B).ljust(l, pad)
    print(x)
elif len % 5 ==3:
    l=len+2
    x = str(B).ljust(l, pad)
    print(x)
elif len % 5 ==4:
    l=len+1
    x = str(B).ljust(l, pad)
    print(x)
elif len % 5 ==0:
    print("Padding not needed")
    x=B

01010011011000010110011101100101011011010110000101110100011010000


In [9]:
x

'01010011011000010110011101100101011011010110000101110100011010000'

In [10]:
length=((x).join(x)).count(x) + 1
length

65

In [11]:
plist=[int(i) for i in str(x)]
plist

[0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0]

In [12]:
n=length/5
n

13

In [13]:
splits = np.array_split(plist,n)
list2=[]
for i in splits:
    print(i)
    #encoding
    word = vector(GF(2),(i))
    E = codes.encoders.LinearCodeGeneratorMatrixEncoder(C)
    A=E.encode(word)
    list2.append(A)
    print("Encoded",A)


[0 1 0 1 0]
Encoded (0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0)
[0 1 1 0 1]
Encoded (0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1)
[1 0 0 0 0]
Encoded (1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0)
[1 0 1 1 0]
Encoded (1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0)
[0 1 1 1 0]
Encoded (0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0)
[1 1 0 0 1]
Encoded (1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1)
[0 1 0 1 1]
Encoded (0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1)
[0 1 1 0 1]
Encoded (0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1)
[0 1 1 0 0]
Encoded (0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0)
[0 0 1 0 1]
Encoded (0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1)
[1 1 0 1 0]
Encoded (1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0)
[0 0 1 1 0]
Encoded (0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0)
[1 0 0 0 0]
Encoded (1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0)


In [14]:
list2

[(0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0),
 (0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1),
 (1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0),
 (1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0),
 (0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0),
 (1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1),
 (0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1),
 (0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1),
 (0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0),
 (0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1),
 (1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0),
 (0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0),
 (1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0)]

In [15]:
#decoding
list3=[]
for x in list2:
    print(x)
    word = vector(GF(2), ((x)))
    w_err = word + vector(GF(2), ((1,0,0,0,0,0,0,0,0,0,0,0,0,0,0)))
    D = C.decoder()
    G=D.decode_to_message(w_err)
    list3.append(G)
    print("Decoded",G)

(0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0)
Decoded (0, 1, 0, 1, 0)
(0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1)
Decoded (0, 1, 1, 0, 1)
(1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0)
Decoded (1, 0, 0, 0, 0)
(1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0)
Decoded (1, 0, 1, 1, 0)
(0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0)
Decoded (0, 1, 1, 1, 0)
(1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1)
Decoded (1, 1, 0, 0, 1)
(0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1)
Decoded (0, 1, 0, 1, 1)
(0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1)
Decoded (0, 1, 1, 0, 1)
(0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0)
Decoded (0, 1, 1, 0, 0)
(0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1)
Decoded (0, 0, 1, 0, 1)
(1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0)
Decoded (1, 1, 0, 1, 0)
(0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0)
Decoded (0, 0, 1, 1, 0)
(1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0)
Decoded (1, 0, 0, 0, 0)


In [16]:
list3

[(0, 1, 0, 1, 0),
 (0, 1, 1, 0, 1),
 (1, 0, 0, 0, 0),
 (1, 0, 1, 1, 0),
 (0, 1, 1, 1, 0),
 (1, 1, 0, 0, 1),
 (0, 1, 0, 1, 1),
 (0, 1, 1, 0, 1),
 (0, 1, 1, 0, 0),
 (0, 0, 1, 0, 1),
 (1, 1, 0, 1, 0),
 (0, 0, 1, 1, 0),
 (1, 0, 0, 0, 0)]

In [17]:
strg=[]
for x in list3:   
    for y in x:
        strg.append(y)
        print(y)

0
1
0
1
0
0
1
1
0
1
1
0
0
0
0
1
0
1
1
0
0
1
1
1
0
1
1
0
0
1
0
1
0
1
1
0
1
1
0
1
0
1
1
0
0
0
0
1
0
1
1
1
0
1
0
0
0
1
1
0
1
0
0
0
0


In [18]:
binr = ''.join(str(e) for e in strg)
print("binary : ",binr)

binary :  01010011011000010110011101100101011011010110000101110100011010000


In [19]:
bl=((binr).join(binr)).count(binr) + 1
bl

65

In [20]:
if bl % 8 ==0:
    val=binr
else:
    m = bl % 8
    val=binr[:-m]

In [21]:
val

'0101001101100001011001110110010101101101011000010111010001101000'

In [22]:
word=bin_to_ascii(val)
word

'Sagemath'