In [1]:
import numpy as np
from sage.crypto.util import ascii_to_bin
from sage.crypto.util import bin_to_ascii
from sage.crypto.util import ascii_integer

In [2]:
C = codes.BCHCode(GF(2), 15, 7, offset=1)
C

/opt/sagemath-9.3/local/lib/python3.7/site-packages/sage/coding/cyclic_code.py:452: FutureWarning: This class/method/function is marked as experimental. It, its functionality or its interface might change without a formal deprecation.
See http://trac.sagemath.org/20284 for details.
  embedding=F_to_Fsplit)


[15, 5] BCH Code over GF(2) with designed distance 7

In [3]:
G=C.generator_matrix()
G

[1 1 1 0 1 1 0 0 1 0 1 0 0 0 0]
[0 1 1 1 0 1 1 0 0 1 0 1 0 0 0]
[0 0 1 1 1 0 1 1 0 0 1 0 1 0 0]
[0 0 0 1 1 1 0 1 1 0 0 1 0 1 0]
[0 0 0 0 1 1 1 0 1 1 0 0 1 0 1]

In [4]:
D = codes.decoders.BCHUnderlyingGRSDecoder(C)
RS=D.grs_code()
RS


[15, 9, 7] Reed-Solomon Code over GF(16)

In [5]:
RS.generator_matrix()

[                   1                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1                    1]
[                   1                   z4                 z4^2                 z4^3               z4 + 1            z4^2 + z4          z4^3 + z4^2        z4^3 + z4 + 1             z4^2 + 1            z4^3 + z4        z4^2 + z4 + 1     z4^3 + z4^2 + z4 z4^3 + z4^2 + z4 + 1      z4^3 + z4^2 + 1             z4^3 + 1]
[                   1                 z4^2               z4 + 1          z4^3 + z4^2             z4^2 + 1        z4^2 + z4 + 1 z4^3 + z4^2 + z4 + 1             z4^3 + 1                   z4                 z4^3            z4^2 + z4        z4^3 + z4 + 1            z4^3 + z4     z4^3 + z4^2 + z4      z4^3 + z4^2 + 1]
[                   1                 z4^3       

In [6]:
RS.dimension()

9

In [7]:
inp = input("Enter any string : ")
print(inp)

Enter any string : Sagemath
Sagemath


In [8]:
bin = BinaryStrings()
B = ascii_to_bin(inp);
print("Converted to Binary : ",B)
list1=[int(i) for i in str(B)]


Converted to Binary :  0101001101100001011001110110010101101101011000010111010001101000


In [9]:
print(list1)


[0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0]


In [10]:
len=len(list1)
len

64

In [11]:
if len % 9==0:
    print("Padding not needed")
    x=B
else:
    pad= '0'
    p = len % 9
    l=len+(9-p)
    x = str(B).ljust(l, pad)
    print(x)

010100110110000101100111011001010110110101100001011101000110100000000000


In [12]:
x

'010100110110000101100111011001010110110101100001011101000110100000000000'

In [13]:
length=((x).join(x)).count(x) + 1
length

72

In [14]:
plist=[int(i) for i in str(x)]
plist

[0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [15]:
n=length/9
n

8

In [16]:
splits = np.array_split(plist,n)
list2=[]
for i in splits:
    print(i)

[0 1 0 1 0 0 1 1 0]
[1 1 0 0 0 0 1 0 1]
[1 0 0 1 1 1 0 1 1]
[0 0 1 0 1 0 1 1 0]
[1 1 0 1 0 1 1 0 0]
[0 0 1 0 1 1 1 0 1]
[0 0 0 1 1 0 1 0 0]
[0 0 0 0 0 0 0 0 0]


In [17]:
splits = np.array_split(plist,n)
list2=[]
for i in splits:
    print(i)
    #encoding
    word = vector(GF(2),(i))
    E = codes.encoders.LinearCodeGeneratorMatrixEncoder(RS)
    A=E.encode(word)
    list2.append(A)
    print("Encoded",A)


[0 1 0 1 0 0 1 1 0]
Encoded (0, z4^3 + z4^2 + 1, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4 + 1, 0, z4^2 + z4 + 1, z4^3 + z4 + 1, z4^3 + 1, z4^2 + z4 + 1, 0, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + 1)
[1 1 0 0 0 0 1 0 1]
Encoded (0, z4^3 + z4, z4^3, z4^3 + z4 + 1, z4^3 + z4^2, 1, z4^3 + 1, z4^3 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2 + z4, 1, z4^3 + z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + z4^2 + 1, z4^3 + 1)
[1 0 0 1 1 1 0 1 1]
Encoded (0, z4, z4^2, z4 + 1, z4 + 1, 0, z4^2 + 1, z4^3 + z4 + 1, z4^2 + 1, z4^2, 0, z4^3 + z4^2 + z4, z4, z4^3 + z4^2 + 1, z4^3 + 1)
[0 0 1 0 1 0 1 1 0]
Encoded (0, 0, 0, z4^2 + z4 + 1, 0, z4^2 + z4, z4^2 + z4, z4^3, 0, z4^2 + z4, z4^2 + z4 + 1, z4^3 + z4, z4^2 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2)
[1 1 0 1 0 1 1 0 0]
Encoded (1, 1, 1, z4^3 + z4, 1, 0, z4^3, z4^3 + z4^2 + z4 + 1, 1, z4^3 + z4^2 + z4 + 1, 0, z4^3 + z4^2, z4^3 + z4^2, z4^3, z4^3 + z4)
[0 0 1 0 1 1 1 0 1]
Encoded (1, z4^3, z4^3 + z4^2, 0, z4^3 + z4^2 + z4 + 1, 0, 0, z4 + 1, z4^3 + z

In [21]:
list2

[(0, z4^3 + z4^2 + 1, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4 + 1, 0, z4^2 + z4 + 1, z4^3 + z4 + 1, z4^3 + 1, z4^2 + z4 + 1, 0, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + 1),
 (0, z4^3 + z4, z4^3, z4^3 + z4 + 1, z4^3 + z4^2, 1, z4^3 + 1, z4^3 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2 + z4, 1, z4^3 + z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + z4^2 + 1, z4^3 + 1),
 (0, z4, z4^2, z4 + 1, z4 + 1, 0, z4^2 + 1, z4^3 + z4 + 1, z4^2 + 1, z4^2, 0, z4^3 + z4^2 + z4, z4, z4^3 + z4^2 + 1, z4^3 + 1),
 (0, 0, 0, z4^2 + z4 + 1, 0, z4^2 + z4, z4^2 + z4, z4^3, 0, z4^2 + z4, z4^2 + z4 + 1, z4^3 + z4, z4^2 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2),
 (1, 1, 1, z4^3 + z4, 1, 0, z4^3, z4^3 + z4^2 + z4 + 1, 1, z4^3 + z4^2 + z4 + 1, 0, z4^3 + z4^2, z4^3 + z4^2, z4^3, z4^3 + z4),
 (1, z4^3, z4^3 + z4^2, 0, z4^3 + z4^2 + z4 + 1, 0, 0, z4 + 1, z4^3 + z4, 0, 0, z4^2, 0, z4, z4^2 + 1),
 (1, z4^2 + z4 + 1, z4^2 + z4, z4^3 + z4^2 + 1, z4^2 + z4 + 1, z4^2 + z4, z4^3 + z4^2 + z4, z4^3 + z4^2 + z4, z4^2 + z4, z4^

In [22]:
list3=[]
for i in list2:
    print(i)
    word = vector(GF(16), ((i)))
    DE =D.grs_decoder()
    G=DE.decode_to_message(word)
    list3.append(G)
    print("Decoded",G)


(0, z4^3 + z4^2 + 1, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4 + 1, 0, z4^2 + z4 + 1, z4^3 + z4 + 1, z4^3 + 1, z4^2 + z4 + 1, 0, z4^3 + z4^2 + z4, z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + 1)
Decoded (0, 1, 0, 1, 0, 0, 1, 1, 0)
(0, z4^3 + z4, z4^3, z4^3 + z4 + 1, z4^3 + z4^2, 1, z4^3 + 1, z4^3 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2 + z4, 1, z4^3 + z4^2 + z4, z4^3 + z4^2 + 1, z4^3 + z4^2 + 1, z4^3 + 1)
Decoded (1, 1, 0, 0, 0, 0, 1, 0, 1)
(0, z4, z4^2, z4 + 1, z4 + 1, 0, z4^2 + 1, z4^3 + z4 + 1, z4^2 + 1, z4^2, 0, z4^3 + z4^2 + z4, z4, z4^3 + z4^2 + 1, z4^3 + 1)
Decoded (1, 0, 0, 1, 1, 1, 0, 1, 1)
(0, 0, 0, z4^2 + z4 + 1, 0, z4^2 + z4, z4^2 + z4, z4^3, 0, z4^2 + z4, z4^2 + z4 + 1, z4^3 + z4, z4^2 + z4 + 1, z4^3 + z4^2 + z4 + 1, z4^3 + z4^2)
Decoded (0, 0, 1, 0, 1, 0, 1, 1, 0)
(1, 1, 1, z4^3 + z4, 1, 0, z4^3, z4^3 + z4^2 + z4 + 1, 1, z4^3 + z4^2 + z4 + 1, 0, z4^3 + z4^2, z4^3 + z4^2, z4^3, z4^3 + z4)
Decoded (1, 1, 0, 1, 0, 1, 1, 0, 0)
(1, z4^3, z4^3 + z4^2, 0, z4^3 + z4^2 + z4 + 1, 0, 0, z4 +

In [23]:
list3


[(0, 1, 0, 1, 0, 0, 1, 1, 0),
 (1, 1, 0, 0, 0, 0, 1, 0, 1),
 (1, 0, 0, 1, 1, 1, 0, 1, 1),
 (0, 0, 1, 0, 1, 0, 1, 1, 0),
 (1, 1, 0, 1, 0, 1, 1, 0, 0),
 (0, 0, 1, 0, 1, 1, 1, 0, 1),
 (0, 0, 0, 1, 1, 0, 1, 0, 0),
 (0, 0, 0, 0, 0, 0, 0, 0, 0)]

In [24]:
for x in list3:
    print(x)

(0, 1, 0, 1, 0, 0, 1, 1, 0)
(1, 1, 0, 0, 0, 0, 1, 0, 1)
(1, 0, 0, 1, 1, 1, 0, 1, 1)
(0, 0, 1, 0, 1, 0, 1, 1, 0)
(1, 1, 0, 1, 0, 1, 1, 0, 0)
(0, 0, 1, 0, 1, 1, 1, 0, 1)
(0, 0, 0, 1, 1, 0, 1, 0, 0)
(0, 0, 0, 0, 0, 0, 0, 0, 0)


In [25]:
strg=[]
for x in list3:
    
    for y in x:
        strg.append(y)
        print(y)

0
1
0
1
0
0
1
1
0
1
1
0
0
0
0
1
0
1
1
0
0
1
1
1
0
1
1
0
0
1
0
1
0
1
1
0
1
1
0
1
0
1
1
0
0
0
0
1
0
1
1
1
0
1
0
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
0
0


In [26]:
binr = ''.join(str(e) for e in strg)
print("binary : ",binr)

binary :  010100110110000101100111011001010110110101100001011101000110100000000000


In [27]:
bl=((binr).join(binr)).count(binr) + 1
bl

72

In [28]:
z=bl-len
if z==0:
    val=binr
else:
    val=binr[:-z]  
val

'0101001101100001011001110110010101101101011000010111010001101000'

In [29]:
val

'0101001101100001011001110110010101101101011000010111010001101000'

In [30]:
word=bin_to_ascii(val)
word

'Sagemath'